### ISSUE TITLE
Standard value for workhours is not correct

### ISSUE THREAD

**Issue by joachimdewaelheyns** [d-mg/time#6] opened 2016-08-25 12:06 UTC
The standard value for work hours is set at 8.5.
To be correct, this should be 8.30 (assuming that the working day is 8h 30m).

**Comment by d-mg** [comment] 2016-08-25 12:23
8.5 should stand for "one hour and a half" this was an easy way to enter the number and it was intended that it would produce 8h 30m. It is not ideal and should be changed. Please create a new issue as an enhancement for this. I would suggest immediatly implementing something like a date picker but only for the hour.

Please check if 8.5 now does produce 8h 30m and close this issue

**Comment by d-mg** [comment] 2016-08-25 12:46
8.5 now results in 8h 30m as intended. We will need to create an enhancement to actually enter minutes instead of just entering an hour.

**Closed by d-mg** 2016-08-25 12:46 UTC
Labels: bug

**Comment by d-mg** [comment] 2016-08-25 21:19
Points not addressed in this will be fixed in: Make work hours input more clear #7
